version: "3.8"

services:

  mongodb:
    container_name: mongodb
    image: mongo:3
    restart: "no"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password